<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 5/25/15
 * Time: 17:13
 */

class ChanelMovie extends DBAccess {
    private static $instance;

    public static function getInstance()
    {
        if(self::$instance==null) {
            self::$instance=new ChanelMovie();
        }
        return self::$instance;
    }

    public function __construct()
    {
        parent::__construct('chanel_movie'); // TODO: Change the autogenerated stub
    }
    public function isExistingRecord($chanel_id,$match_url) {
        $object=$this->getOneObjectByField(array('chanel_id'=>$chanel_id,'match_url'=>$match_url));
        if($object==null) {
            return false;
        } else {
            return true;
        }
    }

}