<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 1/6/15
 * Time: 17:03
 */

class Device extends DBAccess{
    private static $instance;

    public static function getInstance()
    {
        if(self::$instance==null) {
            self::$instance=new Device();
        }
        return self::$instance;
    }

    public function __construct()
    {
        parent::__construct('device'); // TODO: Change the autogenerated stub
    }
    public function authentication() {
        $device_id=InputHelper::getAccessToken();
        if(!$this->isValid($device_id)) {
            throw new APIException("INVALID ACCESS TOKEN",APIException::ERRORCODE_INVALID_TOKEN);
        }
        $this->update(array('last_login'=>array('now()')),array('id'=>$device_id));
        return $device_id;
    }
} 