<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 3/2/15
 * Time: 14:23
 */

class Feedback extends DBAccess{
    private static $instance;

    public static function getInstance()
    {
        if(self::$instance==null) {
            self::$instance=new Feedback();
        }
        return self::$instance;
    }
    public function __construct()
    {
        parent::__construct('feedback'); // TODO: Change the autogenerated stub
    }

}