<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 6/4/15
 * Time: 23:38
 */

class Video extends DBAccess {
    public function __construct()
    {
        parent::__construct("video"); // TODO: Change the autogenerated stub
    }
    private static $instance;

    public static function getInstance()
    {
        if(self::$instance==null) {
            self::$instance=new Video();
        }
        return self::$instance;
    }

}