<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 6/4/15
 * Time: 22:38
 */

class YoutubeChanel extends DBAccess {
    public function __construct()
    {
        parent::__construct("youtube_chanel"); // TODO: Change the autogenerated stub
    }
    private static $instance;

    public static function getInstance()
    {
        if(self::$instance==null) {
            self::$instance=new YoutubeChanel();
        }
        return self::$instance;
    }

}